<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NativeLib>Shared</NativeLib>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OnnxTextEmbeddings/OnnxTextEmbeddings.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
</Project>
