<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/OnnxTextEmbeddings/OnnxTextEmbeddings.csproj" />
    <ProjectReference Include="../../src/OnnxTextEmbeddings.PgVector/OnnxTextEmbeddings.PgVector.csproj" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Pgvector" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
